export const ROLODEX_TYPES = {
  START_ROLODEX_FETCH: "rolodex/START_ROLODEX_FETCH",
  ROLODEX_FETCH_SUCCESS: "rolodex/ROLODEX_FETCH_SUCCESS",
  ROLODEX_FETCH_FAILED: "rolodex/ROLODEX_FETCH_FAILED",
};
